### ISSUE TITLE
Find Youtube Tutorials for Beginners

### ISSUE THREAD

**Issue by rhazama** [TayHern/UCLA-Project-Swim-Tracker#9]

**Comment by rhazama** [comment]
Freestyle: https://www.youtube.com/watch?v=AQy_c30lNjI
Backstroke: https://www.youtube.com/watch?v=MrFt6JHii8w
Breast Stroke: https://www.youtube.com/watch?v=EElzlIMjk_c 
Butterfly: https://www.youtube.com/watch?v=riIyImmuB_M
Flip Turn: https://www.youtube.com/watch?v=GoyXk3xMfKY
Dive: https://www.youtube.com/watch?v=8aY3pr_XWFY

**Comment by TayHern** [comment]
dive video change:
How to dive:
<iframe width="560" height="315" src="https://www.youtube.com/embed/GLMaNiC3egw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
